# Generated by Django 3.0.7 on 2020-07-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
